import * as fs from 'fs';
import * as path from 'path';
import type { SelectionResult } from '@context-pilot-v1/shared';
import { CONTEXT_OUTPUT_FILE, ARCHITECTURE_OUTPUT_FILE } from '@context-pilot-v1/shared';

// ─────────────────────────────────────────────────────────────────────────────
// CONTEXT.md generation
// ─────────────────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

function formatNumber(n: number): string {
  return n.toLocaleString('en-US');
}

function generateContextMd(selection: SelectionResult, root: string): string {
  const { included, excluded, totalTokens, budget } = selection;
  const usagePct = ((totalTokens / budget) * 100).toFixed(1);
  const now = new Date().toISOString();

  let output = `# CONTEXT.md
> Generated by Context Pilot on ${now}
> **Token budget:** ${formatNumber(totalTokens)} / ${formatNumber(budget)} (${usagePct}% used)
> **Files included:** ${included.length} | **Files excluded:** ${excluded.length}

---

`;

  // Include each file with its content
  for (const file of included) {
    const badge = file.isPinned ? ' 📌' : '';
    const scoreStr = (file.score * 100).toFixed(0);
    output += `## \`${file.relativePath}\`${badge}\n`;
    output += `> Score: ${scoreStr}/100 | Tokens: ${formatNumber(file.tokenCount)} | In-degree: ${file.inDegree}\n\n`;

    let content: string;
    try {
      content = fs.readFileSync(file.path, 'utf-8');
    } catch {
      content = '(file could not be read)';
    }

    const ext = file.extension.replace('.', '');
    output += `\`\`\`${ext}\n${content}\n\`\`\`\n\n`;
  }

  // Excluded files summary (top 10)
  if (excluded.length > 0) {
    output += `---\n\n## Excluded files (${excluded.length} total — top ${Math.min(10, excluded.length)} by score)\n\n`;
    output += `| File | Score | Tokens | Reason |\n`;
    output += `|------|-------|--------|--------|\n`;
    for (const file of excluded.slice(0, 10)) {
      const scoreStr = (file.score * 100).toFixed(0);
      output += `| \`${file.relativePath}\` | ${scoreStr}/100 | ${formatNumber(file.tokenCount)} | Over budget |\n`;
    }
  }

  return output;
}

// ─────────────────────────────────────────────────────────────────────────────
// ARCHITECTURE.md generation
// ─────────────────────────────────────────────────────────────────────────────

function generateArchitectureMd(selection: SelectionResult, root: string): string {
  const { included, excluded } = selection;
  const allFiles = [...included, ...excluded];
  const now = new Date().toISOString();

  // Group by directory
  const dirMap = new Map<string, typeof allFiles>();
  for (const file of allFiles) {
    const dir = path.dirname(file.relativePath) || '.';
    if (!dirMap.has(dir)) dirMap.set(dir, []);
    dirMap.get(dir)!.push(file);
  }

  // Top 10 files by score
  const top10 = [...allFiles]
    .sort((a, b) => b.score - a.score)
    .slice(0, 10);

  let output = `# ARCHITECTURE.md
> Generated by Context Pilot on ${now}
> Project root: \`${root}\`

---

## Project structure
| Directory | Files | Total tokens |
|-----------|-------|-------------|
`;

  for (const [dir, files] of [...dirMap.entries()].sort()) {
    const tokens = files.reduce((s, f) => s + f.tokenCount, 0);
    output += `| \`${dir}\` | ${files.length} | ${formatNumber(tokens)} |\n`;
  }

  output += `\n## Top 10 files by architectural importance\n\n`;
  output += `| Rank | File | Score | In-degree | Tokens |\n`;
  output += `|------|------|-------|-----------|--------|\n`;

  for (let i = 0; i < top10.length; i++) {
    const f = top10[i]!;
    const scoreStr = (f.score * 100).toFixed(0);
    const inContext = included.includes(f) ? '✅' : '❌';
    output += `| ${i + 1} ${inContext} | \`${f.relativePath}\` | ${scoreStr}/100 | ${f.inDegree} | ${formatNumber(f.tokenCount)} |\n`;
  }

  output += `\n(✅ = included in CONTEXT.md, ❌ = excluded due to token budget)\n`;

  return output;
}

// ─────────────────────────────────────────────────────────────────────────────
// File writing with .gitignore management
// ─────────────────────────────────────────────────────────────────────────────

function ensureGitignored(root: string, entries: string[]): void {
  const gitignorePath = path.join(root, '.gitignore');
  let content = '';
  try {
    content = fs.readFileSync(gitignorePath, 'utf-8');
  } catch {
    // .gitignore doesn't exist yet, create it
  }

  const missing = entries.filter(e => !content.includes(e));
  if (missing.length === 0) return;

  const addition = `\n# Context Pilot generated files\n${missing.join('\n')}\n`;
  fs.appendFileSync(gitignorePath, addition, 'utf-8');
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export interface ExportResult {
  contextPath: string;
  architecturePath: string;
  totalTokens: number;
  filesIncluded: number;
}

/**
 * Export the selection to CONTEXT.md and ARCHITECTURE.md in the project root.
 * Also ensures these files are in .gitignore.
 */
export async function exportContext(
  selection: SelectionResult,
  root: string
): Promise<ExportResult> {
  const absoluteRoot = path.resolve(root);

  const contextPath = path.join(absoluteRoot, CONTEXT_OUTPUT_FILE);
  const architecturePath = path.join(absoluteRoot, ARCHITECTURE_OUTPUT_FILE);

  const contextContent = generateContextMd(selection, absoluteRoot);
  const architectureContent = generateArchitectureMd(selection, absoluteRoot);

  fs.writeFileSync(contextPath, contextContent, 'utf-8');
  fs.writeFileSync(architecturePath, architectureContent, 'utf-8');

  // Add to .gitignore so they don't get committed
  ensureGitignored(absoluteRoot, [CONTEXT_OUTPUT_FILE, ARCHITECTURE_OUTPUT_FILE]);

  return {
    contextPath,
    architecturePath,
    totalTokens: selection.totalTokens,
    filesIncluded: selection.included.length,
  };
}
